services:

  # ------------
  # LOAD BALANCE
  # ------------
  kong-loadbalancing:
    image: kong:latest
    container_name: kong-loadbalancing
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong-loadbalancing.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./config/kong-loadbalancing.yml:/kong/declarative/kong-loadbalancing.yml
    ports:
      - "8000:8000"   # Porta per i client
    depends_on:
      - service-loadbalancing-1
      - service-loadbalancing-2
      - service-loadbalancing-3
    networks:
      - load-balancing-network

  # ------------
  service-loadbalancing-1:
    build:
      context: ./services/service-loadbalancing/
    container_name: service-loadbalancing-1
    environment:
      SERVICE_NAME: service-1
    networks:
      - load-balancing-network
    ports:
      - "8081:8081"   # Porta per test
  # ------------
  service-loadbalancing-2:
    build:
      context: ./services/service-loadbalancing/
    container_name: service-loadbalancing-2
    environment:
      SERVICE_NAME: service-2
    networks:
      - load-balancing-network
  # ------------
  service-loadbalancing-3:
    build:
      context: ./services/service-loadbalancing/
    container_name: service-loadbalancing-3
    environment:
      SERVICE_NAME: service-3
    networks:
      - load-balancing-network
  # ------------



  # ------------
  # RATE LIMIT
  # ------------
  kong-ratelimiting:
    image: kong:latest
    container_name: kong-ratelimiting
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong-ratelimiting.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./config/kong-ratelimiting.yml:/kong/declarative/kong-ratelimiting.yml
    ports:
      - "8003:8000"   # Porta per i client
    depends_on:
      - service-ratelimiting
    networks:
      - rate-limiting-network

  # ------------
  service-ratelimiting:
    build:
      context: ./services/service-ratelimiting/
    container_name: service-ratelimiting
    networks:
      - rate-limiting-network


networks:
  load-balancing-network:
    driver: bridge
  rate-limiting-network:
    driver: bridge