services:

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - kong-1
      - kong-2
    networks:
      - api-gateway-network

  kong-1:
    image: kong:latest
    container_name: kong-1
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      # KONG_TRUSTED_IPS: "0.0.0.0/0,::/0"        # --> SOLO PER DIMOSTRAZIONE
      # KONG_REAL_IP_HEADER: "X-Forwarded-For"    # --> SOLO PER DIMOSTRAZIONE
      # KONG_REAL_IP_RECURSIVE: "on"              # --> SOLO PER DIMOSTRAZIONE
    volumes:
      - ./config/kong.yml:/kong/declarative/kong.yml
    depends_on:
      - service-loadbalancing-1
      - service-loadbalancing-2
      - service-loadbalancing-3
      - service-security
      - service-ratelimiting
      - service-faulttolerance
    networks:
      - api-gateway-network

  kong-2:
    image: kong:latest
    container_name: kong-2
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      # KONG_TRUSTED_IPS: "0.0.0.0/0,::/0"        # --> SOLO PER DIMOSTRAZIONE
      # KONG_REAL_IP_HEADER: "X-Forwarded-For"    # --> SOLO PER DIMOSTRAZIONE
      # KONG_REAL_IP_RECURSIVE: "on"              # --> SOLO PER DIMOSTRAZIONE
    volumes:
      - ./config/kong.yml:/kong/declarative/kong.yml
    depends_on:
      - service-loadbalancing-1
      - service-loadbalancing-2
      - service-loadbalancing-3
      - service-security
      - service-ratelimiting
      - service-faulttolerance
    networks:
      - api-gateway-network

  service-loadbalancing-1:
    build:
      context: ./services/service-loadbalancing/
    container_name: service-loadbalancing-1
    environment:
      SERVICE_NAME: service-1
    networks:
      - api-gateway-network

  service-loadbalancing-2:
    build:
      context: ./services/service-loadbalancing/
    container_name: service-loadbalancing-2
    environment:
      SERVICE_NAME: service-2
    networks:
      - api-gateway-network

  service-loadbalancing-3:
    build:
      context: ./services/service-loadbalancing/
    container_name: service-loadbalancing-3
    environment:
      SERVICE_NAME: service-3
    networks:
      - api-gateway-network

  service-security:
    build:
      context: ./services/service-security/
    container_name: service-security
    networks:
      - api-gateway-network

  service-ratelimiting:
    build:
      context: ./services/service-ratelimiting/
    container_name: service-ratelimiting
    networks:
      - api-gateway-network

  service-faulttolerance:
    build:
      context: ./services/service-faulttolerance/
    container_name: service-faulttolerance
    networks:
      - api-gateway-network

networks:
  api-gateway-network:
    driver: bridge