spring.application.name=service-faulttolerance
server.port=8084

# Proprietà configurazione Circuit Breaker
resilience4j.circuitbreaker.instances.faultToleranceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.faultToleranceCircuitBreaker.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.faultToleranceCircuitBreaker.sliding-window-size=4
resilience4j.circuitbreaker.instances.faultToleranceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.faultToleranceCircuitBreaker.permitted-number-of-calls-in-half-open-state=2