_format_version: "3.0"

services:
  - name: ratelimiting-service
    protocol: http
    host: service-ratelimiting
    port: 8083
    routes:
      - name: ratelimiting-route
        paths:
          - /ratelimiting
        strip_path: false

plugins:
  - name: rate-limiting
    service: ratelimiting-service
    config:
      minute: 3
      policy: local