events {}

http {
    upstream kong_gateway{
        server kong-1:8000;
        server kong-2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://kong_gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}